---
- name: Install packages necessary for Rails hosting
  apt: pkg={{ item }} state=present
  with_items:
    - apache2
    - apache2-threaded-dev
    - apt-transport-https # So you can install Passenger from repos
    - autoconf
    - automake
    - bison
    - build-essential # To compile Rubies
    - curl
    - git
    - libapr1-dev
    - libcurl4-openssl-dev
    - libffi-dev
    - libgdbm-dev
    - libncurses5-dev
    - libssl-dev
    - libreadline6-dev
    - libtool
    - libxml2-dev
    - libxslt1-dev
    - libyaml-dev
    - make
    - gawk
    - libsqlite3-dev
    - sqlite3
    - bison
    - sudo
  tags:
    - packages

- name: Add GPG key for Phusion Passenger packages
  apt_key: id=AC40B2F7 url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x561F9B9CAC40B2F7 state=present

- name: Add the Phusion Passenger repository (wheezy)
  apt_repository: repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger wheezy main' state=present

- name: Install Phusion Passenger package
  apt: pkg=libapache2-mod-passenger state=installed update_cache=true

- name: Configure mod_passenger's system-wide options
  template: src=passenger.conf.j2 dest="/etc/apache2/conf.d/passenger.conf"

- name: Enable Passenger module
  command: a2enmod passenger
  notify:
  - reload apache
